# Generated by Django 3.1 on 2020-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='position',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('Devops', 'Devops')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='noticeperiod',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previouscompany',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='sapid',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
