# Generated by Django 3.1 on 2020-08-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20200824_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='interviewname',
            field=models.CharField(blank=True, choices=[('HCLPanel1', 'HCLPanel1'), ('HCLPanel2', 'HCLPanel2'), ('IBM', 'IBM')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='interviewtype',
            field=models.CharField(blank=True, choices=[('Teams', 'Teams'), ('Telephonic', 'Telephonic')], max_length=50, null=True),
        ),
    ]
